field: bc99dda4-f230-4723-ba73-4a6b21bf3b73 # Recipe Contents
fieldLayouts:
  0e31f4cf-914f-478c-8c33-1ba4295b669b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ac2d8503-a056-43d7-9113-9acd700efcca # Steps Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c9a17b8-1ee1-4ee7-84e0-9def23149a19
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 540d9651-70a9-4003-8899-65439a885384 # Steps Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5f732a0b-6133-4a89-9e9f-eea5903ce435
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 68fce447-927a-4a98-b552-72c9b4b74787
        userCondition: null
fields:
  540d9651-70a9-4003-8899-65439a885384: # Steps Content
    columnSuffix: uuaiowab
    contentColumnType: text
    fieldGroup: null
    handle: stepsContent
    instructions: null
    name: 'Steps Content'
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - 'Step Instructions'
                -
                  - handle
                  - stepInstructions
                -
                  - width
                  - ''
                -
                  - type
                  - multiline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
  ac2d8503-a056-43d7-9113-9acd700efcca: # Steps Title
    columnSuffix: ryjehqyy
    contentColumnType: text
    fieldGroup: null
    handle: stepsTitle
    instructions: null
    name: 'Steps Title'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeSteps
name: 'Recipe Steps'
sortOrder: 4
