field: bc99dda4-f230-4723-ba73-4a6b21bf3b73 # Recipe Contents
fieldLayouts:
  dc4d0898-bea0-415c-9825-f1211fbb8321:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4eefd5ec-5b69-4e03-b47e-98bedb06c898 # Tip Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 322c4ea0-d291-4436-9024-683490fb3b74
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f0f1a7b5-3262-4b5d-9f4f-4645b09dc2bf
        userCondition: null
fields:
  4eefd5ec-5b69-4e03-b47e-98bedb06c898: # Tip Content
    columnSuffix: sgpgkvwr
    contentColumnType: text
    fieldGroup: null
    handle: tipContent
    instructions: null
    name: 'Tip Content'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: recipeTip
name: 'Recipe Tip'
sortOrder: 5
