field: bc99dda4-f230-4723-ba73-4a6b21bf3b73 # Recipe Contents
fieldLayouts:
  ba674340-e31a-4686-9dd3-77b12cdc2856:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: fd2cb5e8-ccf1-4e8d-971f-4534cf5e4ee9 # Ingredient
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e512080f-0986-467a-a6a7-beb89e4ccc4a
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: d843164e-e1c3-41c2-a79c-2bf4e58d58f1
        userCondition: null
fields:
  fd2cb5e8-ccf1-4e8d-971f-4534cf5e4ee9: # Ingredient
    columnSuffix: xviivhye
    contentColumnType: text
    fieldGroup: null
    handle: ingredient
    instructions: null
    name: Ingredient
    searchable: false
    settings:
      addRowLabel: 'Add a row'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Amount
                -
                  - handle
                  - amount
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Ingredient
                -
                  - handle
                  - ingredient
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: null
      minRows: null
      staticRows: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
handle: recipeIngredients
name: 'Recipe Ingredients'
sortOrder: 1
