fieldLayouts:
  fb7a7167-1845-48e7-897f-d3828ef65c15:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 91de3631-0626-43d9-bdad-70d6712fad8c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f31ba73a-5791-434a-8bb7-e01852ecbf5f # Drink Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6915e93d-731d-448e-b164-011dec06c824
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae6395d0-c095-44f0-91b2-2ecf5d4bafb4 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 854ada47-54da-4af3-a583-2a551b78e771
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: dc464418-ea25-4cfd-ac8e-5545a98c929c
        userCondition: null
handle: allDrinks
hasTitleField: true
name: 'All Drinks'
section: ec1adb86-c0e0-4629-8efc-8ed2e00b5e09 # All Drinks
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
