fieldLayouts:
  453071e4-17ba-4548-97f5-6d5806387d83:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: eb7e4e49-ffa5-4695-904d-c35e0b7ad57e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae6395d0-c095-44f0-91b2-2ecf5d4bafb4 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b8f6010c-2f22-4685-91d3-14d846ff42e1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: f31ba73a-5791-434a-8bb7-e01852ecbf5f # Drink Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b0c0bc2-245a-4fae-baa7-f3d19e7b88e7
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 3198d0f6-49b3-44d9-abd4-d142d7fd00cb
        userCondition: null
handle: allRecipes
hasTitleField: false
name: 'All Recipes'
section: 8c1d350c-3400-4f32-a996-94c5bec04087 # All Recipes
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
