fieldLayouts:
  f6c55802-5cdc-4902-a1e6-9b5786693e79:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: c52d01fb-8349-4e20-a02c-adba1593e822
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ae6395d0-c095-44f0-91b2-2ecf5d4bafb4 # Subtitle
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c8b8771-4093-4764-8864-2d74d678d161
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a21055b3-1c98-4507-ba44-ee2867963ede # Page Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00731a02-16d0-494b-8f7a-9061841364dc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 62f99a75-6423-46fc-88b4-9744492636ac # Page Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: faa12ec3-c536-4d7b-9a48-583c637f506c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1cd252c8-c8a8-4df9-8161-da3a7a8d3630
        userCondition: null
handle: defaultaboutCraftyCoffee_default
hasTitleField: true
name: 'DefaultAbout Crafty Coffee'
section: b187b6de-5693-4b06-9f61-50924ecab14a # About Crafty Coffee
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
