defaultPlacement: end
fieldLayouts:
  cc708293-7f9c-4c9d-81a1-1c890e064b4e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 22de39aa-ef62-4041-b4b0-5020870ea7d1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 08017f5e-acb6-444c-bfae-b669eecb8054 # Style Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50ada63d-4b19-484f-bace-afa56742f08a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 97a4f971-fe4d-431e-8c32-7ea1ea34c5c3
        userCondition: null
handle: drinkStyles
name: 'Drink Styles'
siteSettings:
  e52a3d5a-c741-4dc5-bfe4-d1a6c9049cb5: # alex-craftkit-project
    hasUrls: true
    template: styles_entry.twig
    uriFormat: 'styles/{slug}'
structure:
  maxLevels: 5
  uid: 982cfc4f-23fe-4d31-a4f4-4367d70f497d
