baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-US
name: alex-craftkit-project
primary: true
siteGroup: 25c23f10-9e6b-44df-a6d7-8a99ee9fceb6 # alex-craftkit-project
sortOrder: 1
