fieldLayouts:
  9641016e-db8e-472c-ab07-90ab20bd34b3:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 69c09338-a53d-4872-bb7d-53bf1bf21a69
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ba53c97-c3fc-4c5e-bbc0-6b1c1ee672b9 # Image Alt Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2363268f-760e-4237-b0dd-ab9586266b6f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eab6db22-4dbb-4597-bd2e-9cbe3b8ab25c # Image Quality
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 46a8ad88-0149-4e00-8c9c-16692fb97c3c
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1b340820-8f42-49e7-9f58-94d022f8e960
        userCondition: null
fs: coffeeShop
handle: coffeeShop
name: 'Coffee Shop'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: coffeeShop
transformSubpath: ''
