fieldLayouts:
  bc8b06dc-fbd2-42a1-90e9-67c0fd36551b:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: babdebcd-f353-4503-9094-1a6a707756bc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 1ba53c97-c3fc-4c5e-bbc0-6b1c1ee672b9 # Image Alt Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: de2c0faa-bb7f-406d-a916-85d5341504ac
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: eab6db22-4dbb-4597-bd2e-9cbe3b8ab25c # Image Quality
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0979f006-596a-48fc-9d82-1fd893e7b3aa
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7dbbb3e7-314d-416c-8b8f-44678535aa74
        userCondition: null
fs: drinks
handle: drinks
name: Drinks
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
