dateModified: 1715062730
email:
  fromEmail: dev-test@yoo.digital
  fromName: alex-craftkit-project
  transportType: craft\mail\transportadapters\Sendmail
fs:
  coffeeShop:
    hasUrls: true
    name: 'Coffee Shop'
    settings:
      path: '@webroot/images/uploads/drinks'
    type: craft\fs\Local
    url: '@webr/images/uploads/drinks'
  drinks:
    hasUrls: true
    name: Drinks
    settings:
      path: '@webroot/images/uploads/drinks'
    type: craft\fs\Local
    url: '@web/images/uploads/drinks'
meta:
  __names__:
    0b88ecb2-3a82-4512-b091-3d3357ae96a5: 'Recipe Steps' # Recipe Steps
    0eebc6c7-2c2e-4125-9b71-083f11e1752f: Introduction # Introduction
    1ba53c97-c3fc-4c5e-bbc0-6b1c1ee672b9: 'Image Alt Text' # Image Alt Text
    1c0d27a8-0214-4e5e-b5bf-056229bec07a: 'Drink Style' # Drink Style
    1d056e81-fed5-4961-987f-6dc1e2d46fb5: 'Public Schema' # Public Schema
    2d2c1d4f-b85a-42ad-9fbf-75ddaeb79052: 'Drink Recipe' # Drink Recipe
    3ad1ca16-929b-4a80-8c99-6b4060397459: News # News
    3f6cb7ef-41be-4cbf-9ed0-ab2bb69d5aed: Drink # Drink
    4eefd5ec-5b69-4e03-b47e-98bedb06c898: 'Tip Content' # Tip Content
    07a252a6-df96-4b03-b247-01289eba7e01: 'All Recipes' # All Recipes
    8c1d350c-3400-4f32-a996-94c5bec04087: 'All Recipes' # All Recipes
    9c3a2d0d-001e-4c0a-9927-6a785ea78d51: 'Coffee Shop' # Coffee Shop
    20b9314a-0364-44c9-a77a-f14c79315411: 'Banner Image' # Banner Image
    25c23f10-9e6b-44df-a6d7-8a99ee9fceb6: alex-craftkit-project # alex-craftkit-project
    28b36b86-72f6-4b2c-a601-19815bd2f0e9: Drinks # Drinks
    29e446ac-2469-40bd-ab37-515ea72d24d1: Common # Common
    56cb24e9-9490-4041-b9d0-cd66d05df7db: 'News Body' # News Body
    58b93e3f-af7b-4c45-98af-80f323172f96: 'Image Caption' # Image Caption
    62f99a75-6423-46fc-88b4-9744492636ac: 'Page Copy' # Page Copy
    87e217bf-9a39-4fd8-a65d-ad253be32916: 'All Drinks' # All Drinks
    96abb758-9f11-445b-b078-c0436d4c991d: Recipes # Recipes
    254e7272-8e43-44f0-8ff1-9c16eee00c4c: 'Recipe Copy' # Recipe Copy
    389fec98-5d8e-498c-acde-47dff8149620: 'Drink Styles' # Drink Styles
    423b7483-da6a-4f4f-a880-17da2bc4c29b: 'Recipe Ingredients' # Recipe Ingredients
    540d9651-70a9-4003-8899-65439a885384: 'Steps Content' # Steps Content
    0945c95a-991c-45a2-a334-783315082e98: 'Body Content' # Body Content
    992a490a-fba4-4f64-8dc5-3a3c992a1917: Homepage # Homepage
    08017f5e-acb6-444c-bfae-b669eecb8054: 'Style Description' # Style Description
    1622926a-7b7d-4ac2-86b3-bf22f2ccbf61: Default # Default
    a44e5ac3-c8e7-4152-9c69-8d62cdcde787: 'About Crafty Coffee' # About Crafty Coffee
    a21055b3-1c98-4507-ba44-ee2867963ede: 'Page Intro' # Page Intro
    a49090dd-356c-4ace-b91c-a20841e7b268: Default # Default
    ac2d8503-a056-43d7-9113-9acd700efcca: 'Steps Title' # Steps Title
    ae6395d0-c095-44f0-91b2-2ecf5d4bafb4: Subtitle # Subtitle
    b187b6de-5693-4b06-9f61-50924ecab14a: 'About Crafty Coffee' # About Crafty Coffee
    b511ce47-b1be-429f-b371-5005d5a7eb45: News # News
    b40445cc-2ed2-46b9-9772-5a97e109afa5: 'Recipe Tip' # Recipe Tip
    b7330105-be23-43ba-8166-10d133ce2824: 'DefaultAbout Crafty Coffee' # DefaultAbout Crafty Coffee
    bc99dda4-f230-4723-ba73-4a6b21bf3b73: 'Recipe Contents' # Recipe Contents
    c6574eee-5452-4b59-8736-69ce0d556df4: Image # Image
    cde5ac79-3ee7-49b3-8aed-86673232cce4: Simple # Simple
    d1fc5780-78e6-405c-a7f7-c85ce822a181: 'Recipe Image' # Recipe Image
    d59d1159-2e3b-451f-9eed-941de1451f16: Drinks # Drinks
    dd01bfb1-f5c2-4d76-8162-114e84cca330: 'Drink Styles' # Drink Styles
    e52a3d5a-c741-4dc5-bfe4-d1a6c9049cb5: alex-craftkit-project # alex-craftkit-project
    e594e887-3561-4d97-bd94-7a9fa33edb04: Recipes # Recipes
    e74106f0-2b6a-4d6b-b3f9-b3956425511a: Excerpt # Excerpt
    eab6db22-4dbb-4597-bd2e-9cbe3b8ab25c: 'Image Quality' # Image Quality
    ec1adb86-c0e0-4629-8efc-8ed2e00b5e09: 'All Drinks' # All Drinks
    ed6d4cf3-57d1-49c1-bcb6-76c31f219301: Drinks # Drinks
    f7e0d758-7654-42ff-8eb9-800e5901bc58: Homepage # Homepage
    f31ba73a-5791-434a-8bb7-e01852ecbf5f: 'Drink Image' # Drink Image
    f1170bf8-158f-4ac9-a56c-ce4956a03b20: Writer # Writer
    fd2cb5e8-ccf1-4e8d-971f-4534cf5e4ee9: Ingredient # Ingredient
plugins:
  architect:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
  contact-form:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  contact-form-honeypot:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  cp-field-inspect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  craft-components:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: 9EKH8OVNSUDL3J346JF9JCSP
    schemaVersion: 4.0.0
  project-extension:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: YLMW0J46IUV0LLVME9CQQNT7
    schemaVersion: 3.0.12
  super-table:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
system:
  edition: solo
  live: true
  name: test-setup-project
  retryDuration: null
  schemaVersion: 4.5.3.0
  timeZone: Europe/Zurich
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
