defaultPlacement: end
enableVersioning: true
handle: allDrinks
name: 'All Drinks'
propagationMethod: all
siteSettings:
  e52a3d5a-c741-4dc5-bfe4-d1a6c9049cb5: # alex-craftkit-project
    enabledByDefault: true
    hasUrls: true
    template: _entry-types/drinks/index.twig
    uriFormat: drinks
type: single
