defaultPlacement: end
enableVersioning: true
handle: allRecipes
name: 'All Recipes'
propagationMethod: all
siteSettings:
  e52a3d5a-c741-4dc5-bfe4-d1a6c9049cb5: # alex-craftkit-project
    enabledByDefault: true
    hasUrls: true
    template: _entry-types/recipes/index.twig
    uriFormat: recipes
type: single
